// Centralized brand logo URLs - all verified via Wikimedia Commons API
// Brands without verified logos fall back to letter initial in components

export const brandLogos: Record<string, string> = {
  'rolex': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Rolex_wordmark_logo.svg/200px-Rolex_wordmark_logo.svg.png',
  'omega': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Omega_Logo.svg/200px-Omega_Logo.svg.png',
  'patek-philippe': 'https://upload.wikimedia.org/wikipedia/de/thumb/5/5f/Logo_Patek_Philippe.svg/200px-Logo_Patek_Philippe.svg.png',
  'audemars-piguet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Logo_Audemars_Piguet.svg/200px-Logo_Audemars_Piguet.svg.png',
  'cartier': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Cartier_logo.svg/200px-Cartier_logo.svg.png',
  'seiko': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Seiko_logo.svg/200px-Seiko_logo.svg.png',
  'grand-seiko': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Grand_Seiko_Logo.svg/200px-Grand_Seiko_Logo.svg.png',
  'tudor': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Tudor_%28Uhrenmarke%29_logo.svg/200px-Tudor_%28Uhrenmarke%29_logo.svg.png',
  'tag-heuer': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/TAG_Heuer_Logo.svg/200px-TAG_Heuer_Logo.svg.png',
  'iwc': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/International_Watch_Company_logo.svg/200px-International_Watch_Company_logo.svg.png',
  'jaeger-lecoultre': 'https://upload.wikimedia.org/wikipedia/commons/3/33/Jaeger-LeCoultre_Logo_%28cropped%29.png',
  'breitling': 'https://upload.wikimedia.org/wikipedia/fr/thumb/8/8b/Breitling_logo.svg/200px-Breitling_logo.svg.png',
  'longines': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Longines_wordmark_logo.svg/250px-Longines_wordmark_logo.svg.png',
  'tissot': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Tissot_Logo_%282023%29.png/250px-Tissot_Logo_%282023%29.png',
  'hublot': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Hublot-logo.svg/250px-Hublot-logo.svg.png',
  'hamilton': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Hamilton_Watch_Company_Logo.svg/250px-Hamilton_Watch_Company_Logo.svg.png',
  'panerai': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Panerai_logo.svg/250px-Panerai_logo.svg.png',
  'vacheron-constantin': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Vacheron_logo.svg/250px-Vacheron_logo.svg.png',
  'bulgari': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Bulgari_logo.svg/250px-Bulgari_logo.svg.png',
  'citizen': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Citizen_logo.svg/250px-Citizen_logo.svg.png',
  'casio': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Casio_logo.svg/250px-Casio_logo.svg.png',
  'swatch': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Swatch_Logo.svg/250px-Swatch_Logo.svg.png',
  'rado': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Rado_%28Uhrenmarke%29_logo.svg/250px-Rado_%28Uhrenmarke%29_logo.svg.png',
  'mido': 'https://upload.wikimedia.org/wikipedia/commons/8/89/Mido-logo.png',
  'certina': 'https://upload.wikimedia.org/wikipedia/commons/5/57/Certina-Logo.png',
  'bulova': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Bulova_logo.svg/250px-Bulova_logo.svg.png',
  'nomos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Nomos_Glash%C3%BCtte.svg/250px-Nomos_Glash%C3%BCtte.svg.png',
  'nomos-glashutte': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Nomos_Glash%C3%BCtte.svg/250px-Nomos_Glash%C3%BCtte.svg.png',
  'a-lange-sohne': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Alange_soehne_logo.svg/250px-Alange_soehne_logo.svg.png',
  'blancpain': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Blancpain_logo.svg/250px-Blancpain_logo.svg.png',
  'breguet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Breguet_logo.png/250px-Breguet_logo.png',
  'g-shock': 'https://upload.wikimedia.org/wikipedia/commons/a/ae/G-Shock_logo.png',
  'oris': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Oris_logo.svg/250px-Oris_logo.svg.png',
  'piaget': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Piaget_logo.svg/250px-Piaget_logo.svg.png',
  'zenith': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Zenith_logo.svg/250px-Zenith_logo.svg.png',
};
