// Centralized brand logo URLs from Wikimedia Commons
// Used across BrandCard, brand pages, homepage, etc.

export const brandLogos: Record<string, string> = {
  'rolex': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Rolex_wordmark_logo.svg/200px-Rolex_wordmark_logo.svg.png',
  'omega': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Omega_Logo.svg/200px-Omega_Logo.svg.png',
  'patek-philippe': 'https://upload.wikimedia.org/wikipedia/de/thumb/5/5f/Logo_Patek_Philippe.svg/200px-Logo_Patek_Philippe.svg.png',
  'audemars-piguet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Logo_Audemars_Piguet.svg/200px-Logo_Audemars_Piguet.svg.png',
  'cartier': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Cartier_logo.svg/200px-Cartier_logo.svg.png',
  'seiko': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Seiko_logo.svg/200px-Seiko_logo.svg.png',
  'grand-seiko': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Grand_Seiko_Logo.svg/200px-Grand_Seiko_Logo.svg.png',
  'tudor': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Tudor_%28Uhrenmarke%29_logo.svg/200px-Tudor_%28Uhrenmarke%29_logo.svg.png',
  'tag-heuer': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/TAG_Heuer_Logo.svg/200px-TAG_Heuer_Logo.svg.png',
  'iwc': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/International_Watch_Company_logo.svg/200px-International_Watch_Company_logo.svg.png',
  'jaeger-lecoultre': 'https://upload.wikimedia.org/wikipedia/commons/3/33/Jaeger-LeCoultre_Logo_%28cropped%29.png',
  'breitling': 'https://upload.wikimedia.org/wikipedia/fr/thumb/8/8b/Breitling_logo.svg/200px-Breitling_logo.svg.png',
  'longines': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Logo_Longines.svg/200px-Logo_Longines.svg.png',
  'tissot': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Tissot_Logo.svg/200px-Tissot_Logo.svg.png',
  'hamilton': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Hamilton_Watch_Company_logo.svg/200px-Hamilton_Watch_Company_logo.svg.png',
  'hublot': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Hublot_logo.svg/200px-Hublot_logo.svg.png',
  'zenith': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Zenith_Logo.svg/200px-Zenith_Logo.svg.png',
  'panerai': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Officine_Panerai_logo.svg/200px-Officine_Panerai_logo.svg.png',
  'vacheron-constantin': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Vacheron_Constantin_logo.svg/200px-Vacheron_Constantin_logo.svg.png',
  'a-lange-sohne': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/A._Lange_%26_S%C3%B6hne_Logo.svg/200px-A._Lange_%26_S%C3%B6hne_Logo.svg.png',
  'bulgari': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Bulgari_logo.svg/200px-Bulgari_logo.svg.png',
  'citizen': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Citizen_logo.svg/200px-Citizen_logo.svg.png',
  'casio': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Casio_logo.svg/200px-Casio_logo.svg.png',
  'g-shock': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/G-Shock_logo.svg/200px-G-Shock_logo.svg.png',
  'orient': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Orient_Watch_logo.svg/200px-Orient_Watch_logo.svg.png',
  'frederique-constant': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Logo_Frederique_Constant.svg/200px-Logo_Frederique_Constant.svg.png',
  'nomos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/NOMOS_Glashutte_Logo.svg/200px-NOMOS_Glashutte_Logo.svg.png',
  'swatch': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Logo_Swatch.svg/200px-Logo_Swatch.svg.png',
  'rado': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Rado_%28Uhrenmarke%29_logo.svg/200px-Rado_%28Uhrenmarke%29_logo.svg.png',
  'mido': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Mido_Logo.svg/200px-Mido_Logo.svg.png',
  'certina': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Certina_logo.svg/200px-Certina_logo.svg.png',
  'piaget': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Piaget_Logo.svg/200px-Piaget_Logo.svg.png',
  'bulova': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Bulova_Logo.svg/200px-Bulova_Logo.svg.png',
  'titan': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Titan_Company_Logo.svg/200px-Titan_Company_Logo.svg.png',
};
